name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Build and Test with Maven
      timeout-minutes: 15
      run: ./mvnw -B verify

    - name: Get JaCoCo Coverage
      id: coverage  
      run: |
        coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
        echo "COVERAGE=$coverage" >> $GITHUB_ENV

    - name: Fail if coverage has not improved.
      run: |
        coverage=$COVERAGE
        threshold=24.46
        if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
          echo "Coverage is not improved."
          exit 1
        else
          echo "New coverage: $coverage%. Coverage is improved!"
        fi
      
    - name: Run Tests with Memory Dump on Failure
      run: |
        echo "Starting tests with flag: -XX:+HeapDumpOnOutOfMemoryError"
        echo "If memory acts up, we've got a little trip to the dump (memory dump) planned!"
        ./mvnw -B verify -DargLine="-XX:+HeapDumpOnOutOfMemoryError"
        echo "Tests completed! Thankfully, we didn t need to take out the big guns."

    - name: Run Tests with Optimized Garbage Collection (G1)
      run: |
        echo "Starting tests with flag: -XX:+UseG1GC"
        echo "The G1 Garbage Collector is on duty, taking care of all those digital scraps."
        ./mvnw -B verify -DargLine="-XX:+UseG1GC"
        echo "Tests completed! Thanks to G1 for keeping things nice and tidy."

    - name: Run Tests with Custom Stack Size
      run: |
        echo "Starting tests with a custom stack size: -Xss512k"
        echo "We're limiting the stack space a bit... let's hope the code isn t too stack-hungry!"
        ./mvnw -B verify -DargLine="-Xss512k"
        echo "Tests completed successfully, and the stack held up just fine!"



    



